#include "KeplerOpenBOT.h"

void setup() {
  KeplerOpenBOT_INIT();
  WRITE_LCD_CONTRAST(190);
  WRITE_MOTOR(ML, 60);
  WRITE_MOTOR(MR, 60);
  SLEEP(3000);
  WRITE_MOTOR(ML, 0);
  WRITE_MOTOR(MR, 0);
  SLEEP(4000);
  WRITE_MOTOR(ML, 80);
  WRITE_MOTOR(MR, 80);
  SLEEP(4000);
  WRITE_MOTOR(ML, -75);
  WRITE_MOTOR(MR, -75);
  SLEEP(2000);
  WRITE_MOTOR(ML, 0);
  WRITE_MOTOR(MR, 0);
  SLEEP(2000);
  WRITE_MOTOR(ML, 0);
  WRITE_MOTOR(MR, 40);
  SLEEP(5000);
  WRITE_MOTOR(ML, -70);
  WRITE_MOTOR(MR, -70);
  SLEEP(3000);
  WRITE_MOTOR(ML, 0);
  WRITE_MOTOR(MR, 0);
}

void loop() {
}

